
export const ConfigActions = {
    CONFIG_PENDING: 'CONFIG_PENDING',
    CONFIG_FAILURE: 'CONFIG_FAILURE',
    CONFIG_SUCCESS: 'CONFIG_SUCCESS'
};

export const UsersActions = {
    LOGGED_IN: 'USER_LOGGED_IN',
    SKIPPED_LOGIN: 'USER_SKIPPED_LOGIN',
    LOGGED_OUT: 'USER_LOGGED_OUT'
};

export const PostActions = {
    GET_POSTS: 'POST_GET_POSTS',
    GET_SINGLE_POST: 'POST_GET_SINGLE_POST'
};